# Name of video you want to track
# E.g., mating1, mating2, mating3, etc. as seen in the 'videos' directory
video_name: mating7

# ---------------------------------------------------------------
# DeepSORT tracker
# ---------------------------------------------------------------

# If you wish to use the modified DeepSORT version, set to True else, False
modify: True


# ---------------------------------------------------------------
# segmentation.py
# ---------------------------------------------------------------

# To run `segmentation.py` edit here.
segmentation:
 sam: True


# ---------------------------------------------------------------
# worm_tracker.py
# ---------------------------------------------------------------

# To run `worm_tracker.py`, edit here.
worm_tracker:
 sam: True

# This is used to test the system's accuracy.
test: False